--TB3D 1.0.9.9.9.8
function my_ver() return "1.0.9.9.9.8" end
--optional file presently used for testing

function init()			--called  from bind_stalker.net_spawn()
	-------------------------------------test setcion-------------------------------------------
	--TB3D_Services.move_actor(60.4173583984375,29.2011890411377,164.266647338867)
	--tb3d_net_manager.network_send("test")
	--------------------------------------------------------------------------------------------
end