--TB3D 1.0.9.9.4.0 redone, atp, protected when no actor or gulag, esc killers
function my_ver() return "1.0.9.9.4.0" end
local t = {}

function load_job(sj, gname, type, squad, groups)
    if type == "dead_city_naymitu" then							-- Gulag mercenaries MG
        t = { section = "logic@dead_city_naymitu_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_walker5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_naymitu_kamp5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "dead_city_banda" then						-- Gulag Bandos at MG
        t = { section = "logic@dead_city_banda_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_walker5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_banda_kamp5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "dead_city_stalkers" then				-- Gulag colliding in the MG
        t = { section = "logic@dead_city_stalkers_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_stalkers_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_stalkers_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_stalkers_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@dead_city_stalkers_kamp5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "esc_podmoga_bandit" then					-- Gulag reinforcements bandits in cordon
        t = { section = "logic@esc_podmoga_bandit_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@esc_podmoga_bandit_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@esc_podmoga_bandit_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@esc_podmoga_bandit_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
	elseif type == "generators_flesh1" then					--' Flesh on the generators
	  t = { section = "logic@generators_flesh1", 
	   idle = 0,
	   prior = 5, state = {0},
	   in_rest = "", out_rest = ""
	  }
	  table.insert(sj, t)
	  t = { section = "logic@generators_flesh1", 
	   idle = 0,
	   prior = 5, state = {0},
	   in_rest = "", out_rest = ""
	  }
	  table.insert(sj, t)
	  t = { section = "logic@generators_flesh1", 
	   idle = 0,
	   prior = 5, state = {0},
	   in_rest = "", out_rest = ""
	  }
	  t = { section = "logic@generators_flesh1", 
	   idle = 0,
	   prior = 5, state = {0},
	   in_rest = "", out_rest = ""
	  }
	  table.insert(sj, t)
	elseif type == "generators_tushkano" then					--' Tushkany on generators
		t = { section = "logic@generators_tushkano", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_tushkano", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_tushkano", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		t = { section = "logic@generators_tushkano", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_tushkano", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_tushkano", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "generators_snork" then								--' Snork on generators
		t = { section = "logic@generators_snork", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_snork", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_snork", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		t = { section = "logic@generators_snork", 
		idle = 0,
		prior = 5, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "generators_gigant" then				--' Giant generators
		t = { section = "logic@generators_gigant", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "generators_chimera" then					--' Chimera generators
		t = { section = "logic@generators_chimera", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_chimera", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "generators_kaban" then					--' 3kabana on generators
		t = { section = "logic@generators_kaban", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_kaban", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@generators_kaban", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "gener_kaban_two" then				--' 5kabanov have Betonka on generators
		t = { section = "logic@gener_kaban_two", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gener_kaban_two", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gener_kaban_two", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gener_kaban_two", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@gener_kaban_two", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "aver_kaban_gulag" then					--' 10kabanov on Avery
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@aver_kaban_gulag", 
		idle = 0,
		prior = 20, state = {0},
		in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
    elseif type == "aver_hunter" then						-- Gulag GREEN ON EARTH Undiscovered
        t = { section = "logic@aver_hunter_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@aver_hunter_kamp2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@aver_hunter_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@aver_hunter_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "generators_orly" then					-- The Gulag of neutrals on the generators
        t = { section = "logic@generators_orly_zemlyk",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_orly_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_orly_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_orly_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_orly_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_orly_kamp5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_orly_kamp6",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "black_generators" then					-- Gulag black on generators
        t = { section = "logic@black_generators_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker6",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker7",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker8",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker9",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@black_generators_walker10",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "hospital_black" then						-- Gulag black at the Hospital
        t = { section = "logic@hospital_black_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@hospital_black_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@hospital_black_walker3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "generators_svoboda" then					-- Gulag Freedom on generators
        t = { section = "logic@generators_svoboda_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_svoboda_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_svoboda_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@generators_svoboda_kamp4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "village_gulag_big" then						-- Gulag colliding in the village at the headquarters
        t = { section = "logic@village_gulag_big_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_big_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_big_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_big_kamp4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_big_walker5",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_big_walker6",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_big_walker7",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "village_gulag_small" then					-- Gulag collide in a village near the fire
        t = { section = "logic@village_gulag_small_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_small_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@village_gulag_small_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "lost_village_bandit" then						-- Gulag bandits in the countryside
        t = { section = "logic@lost_village_bandit_walker1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@lost_village_bandit_walker2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@lost_village_bandit_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@lost_village_bandit_kamp4",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "rost_naem_koster" then						-- mikrogulag mercenaries on the germ of a campfire
        t = { section = "logic@rost_naem_koster_kamp1",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@rost_naem_koster_kamp2",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@rost_naem_koster_kamp3",
            idle = 0,
            prior = 10, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
    elseif type == "warlab_svobodovzu" then						-- Gulag Freedom on VARLABE
        t = { section = "logic@warlab_svobodovzu_walker1",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker2",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker3",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker4",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_kamp5",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_kamp6",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker7",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_kamp8",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_kamp9",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker10",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_kamp11",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_kamp12",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker13",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker14",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker15",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker16",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker17",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker18",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
        t = { section = "logic@warlab_svobodovzu_walker19",
            idle = 0,
            prior = 5, state = {0},
            in_rest = "", out_rest = ""
        }
        table.insert(sj, t)
	elseif type == "atp_fabrika_bandit" then						--' Bandits on the ATP
		t = { section = "logic@atp_fabrika_bandit_walker1",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)		
		t = { section = "logic@atp_fabrika_bandit_walker5",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker6",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker7",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker8",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker9",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker10",
			idle = 0,
  		     prior = 5, state = {0},
              in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker11",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker12",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@atp_fabrika_bandit_walker13",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker14",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker15",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker16",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker17",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker18",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
               t = { section = "logic@atp_fabrika_bandit_walker19",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
               t = { section = "logic@atp_fabrika_bandit_walker20",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
               t = { section = "logic@atp_fabrika_bandit_walker21",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
        table.insert(sj, t)
               t = { section = "logic@atp_fabrika_bandit_walker22",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
       table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker23",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
           		}
      table.insert(sj, t)
                t = { section = "logic@atp_fabrika_bandit_walker24",
			idle = 0,
			prior = 5, state = {0},
              in_rest = "", out_rest = ""
          		}
      table.insert(sj, t)
	elseif type == "labirint_monolit" then							--' Monolith in a maze
		t = { section = "logic@labirint_monolit_walker1",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker2",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker3",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker4",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)		
		t = { section = "logic@labirint_monolit_walker5",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker6",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker7",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker8",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker9",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker10",
			idle = 0,
  		     prior = 10, state = {0},
              in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker11",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker12",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
		t = { section = "logic@labirint_monolit_walker13",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
                  t = { section = "logic@labirint_monolit_kamp14",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                  t = { section = "logic@labirint_monolit_kamp15",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                  t = { section = "logic@labirint_monolit_kamp16",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                  t = { section = "logic@labirint_monolit_kamp17",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
                  t = { section = "logic@labirint_monolit_kamp18",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
                t = { section = "logic@labirint_monolit_kamp19",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
                t = { section = "logic@labirint_monolit_kamp20",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
           		}
		table.insert(sj, t)
	elseif type == "land_arhara_sniper" then					--' Snipers on the Reconoitered Earth base
		t = { section = "logic@land_arhara_sniper_snip1",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@land_arhara_sniper_snip2",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@land_arhara_sniper_snip3",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@land_arhara_sniper_snip4",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
		t = { section = "logic@land_arhara_sniper_snip5",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
            		}
		table.insert(sj, t)
	elseif type == "aver_arhara_sniper_mikrogulag1" then				--' Snipers on the unexplored Earth mikrogulag_1
		t = { section = "logic@aver_arhara_sniper_mikrogulag1_tip1",
			idle = 0,
			prior = 30, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_mikrogulag1_tip2",
			idle = 0,
			prior = 30, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_mikrogulag1_tip3",
			idle = 0,
			prior = 30, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
	elseif type == "aver_arhara_sniper_makrogulag2" then					--' Snipers on the unexplored Earth gulag_2
		t = { section = "logic@aver_arhara_sniper_makrogulag2_vrag1",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_makrogulag2_vrag2",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_makrogulag2_vrag3",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_makrogulag2_vrag4",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_makrogulag2_vrag5",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@aver_arhara_sniper_makrogulag2_vrag6",
			idle = 0,
			prior = 15, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
	elseif type == "aver_otshelnik" then						--- People Hermit ---
         t = { section = "logic@aver_otshelnik_zimovie3",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
         t = { section = "logic@aver_otshelnik_zimovie4",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
         t = { section = "logic@aver_otshelnik_zimovie5",
			idle = 0,
			prior = 10, state = {0},
              in_rest = "", out_rest = ""
          		}
		table.insert(sj, t)
	elseif type == "atp_brigada" then					--- Kalinin and his men ---
		t = { section = "logic@atp_brigada_walker1",
			idle = 0,
			prior = 10, state = {0},
               online = true,
			in_rest = "", out_rest = ""
                  }
        table.insert(sj, t)
		t = { section = "logic@atp_brigada_kamp2",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@atp_brigada_walker3",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@atp_brigada_walker4",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@atp_brigada_walker5",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
		t = { section = "logic@atp_brigada_walker6",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = ""
             		}
		table.insert(sj, t)
	elseif type == "esc_new_lager" then							--- new camp ---
		t = { section = "logic@esc_new_lager_esc_kostya",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "svalka_lager" then								--- svalka camp ---	
		t = { section = "logic@svalka_lager_esc_kostya",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "bar_lager" then								--- bar camp ---
		t = { section = "logic@bar_lager_esc_kostya",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
    elseif type == "as_lager" then								--- as camp ---	
		t = { section = "logic@as_lager_esc_kostya",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
    elseif type == "pripyat_lager" then								--- pripyat camp ---
		t = { section = "logic@pripyat_lager_esc_kostya",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_blokpost" then								--' Escape blockpost
		t = { section = "logic@esc_blockpost_patrol1",
			idle = 0,
			prior = 8, state = {0},
			position_threshold = 100,
			online = true,
			in_rest = "", out_rest = "esc_blockpost_patrol_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_follower1",
			idle = 0,
			prior = 7, state = {0},
			position_threshold = 100,
			online = true,
			in_rest = "", out_rest = "esc_blockpost_patrol_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_follower2",
			idle = 0,
			prior = 7, state = {0},
			position_threshold = 100,
			online = true,
			in_rest = "", out_rest = "esc_blockpost_patrol_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_commander_day",
			idle = 0,
			prior = 100, state = {0,2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone",
			predicate = function(obj_info)
			            	return obj_info and obj_info.name == "esc_blokpost_commander"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_post1",
			idle = 0,
			prior = 8, state = {0,1,2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_post2",
			idle = 0,
			prior = 8, state = {0,1,2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_camper_day",
			idle = 0,
			prior = 6, state = {0,2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_patrol_yard",
			idle = 0,
			prior = 5, state = {0,1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_watch_tv1",
			idle = 0,
			prior = 2, state = {0},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_watch_tv2",
			idle = 0,
			prior = 2, state = {0},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_kamp1",
			idle = 0,
			prior = 4, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_kamp1",
			idle = 0,
			prior = 4, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_kamp2",
			idle = 0,
			prior = 10, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone",
			predicate = function(obj_info)
			            	return obj_info and obj_info.name == "esc_blokpost_commander"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep1",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep2",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep3",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_sleep4",
			idle = 0,
			prior = 2, state = {1},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_comander_guard1",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_comander_guard2",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_camper1",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_camper2",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_alarm_patrol1",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_blockpost_alarm_patrol2",
			idle = 0,
			prior = 6, state = {2},
			position_threshold = 100,
--			online = true,
			in_rest = "", out_rest = "escape_blockpost_zone"
		}
		table.insert(sj, t)
	elseif type == "esc_specnaz" then						--' Riot police at a checkpoint
		t = { section = "logic@esc_specnaz_kamp",
			idle = 0,
			prior = 5, state = {0},
--			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_kamp",
			idle = 0,
			prior = 5, state = {0},
--			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_kamp",
			idle = 0,
			prior = 5, state = {0},
--			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_kamp",
			idle = 0,
			prior = 5, state = {0},
--			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_kamp",
			idle = 0,
			prior = 5, state = {0},
--			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_kamp",
			idle = 0,
			prior = 5, state = {0},
--			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_raid1",
			idle = 0,
			prior = 10, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_raid2",
			idle = 0,
			prior = 10, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_follower1",
			idle = 0,
			prior = 7, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_follower2",
			idle = 0,
			prior = 7, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_follower3",
			idle = 0,
			prior = 7, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_specnaz_follower4",
			idle = 0,
			prior = 7, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_lager" then					--' Camp newcomers to Escape
		t = { section = "logic@esc_lager_zoneguard1",		-- guards
			idle = 0,
			prior = 9, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_zoneguard2",
			idle = 0,
			prior = 9, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_walker3",
			idle = 0,
			prior = 8, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_walker4",
			idle = 0,
			prior = 8, state = {0, 1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",		-- campfire day
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 6, state = {0},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_volk",		-- Wolf, himself.
			idle = 0,
			prior = 16, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			predicate = function(obj_info)
        					return obj_info and obj_info.profile_name == "esc_wolf"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_shustryi",		-- Nimble
			idle = 0,
			prior = 16, state = {0,1},
            online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.profile_name == "esc_shustryi"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 16, state = {2},
            online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.profile_name == "esc_shustryi"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_fanat",		-- Fan
			idle = 0,
			prior = 16, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			predicate = function(obj_info)
        					return obj_info and obj_info.profile_name == "esc_fanat"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_sleeper1",		-- sleeping at night
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_sleeper2",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 3, state = {1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		-- sleeping at night and dnei
		t = { section = "logic@esc_lager_sleeper5",
			idle = 0,
			prior = 5, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_kamp1",
			idle = 0,
			prior = 0, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_sleeper7",
			idle = 0,
			prior = 0, state = {0,1},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)

		t = { section = "logic@esc_lager_defend1",
			idle = 0,
			prior = 15, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend2",
			idle = 0,
			prior = 14, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend3",
			idle = 0,
			prior = 13, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend4",
			idle = 0,
			prior = 12, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend5",
			idle = 0,
			prior = 11, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend6",
			idle = 0,
			prior = 10, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend7",
			idle = 0,
			prior = 9, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend8",
			idle = 0,
			prior = 8, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend9",
			idle = 0,
			prior = 16, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker1"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend10",
			idle = 0,
			prior = 16, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_vagon_wounded"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend11",
			idle = 0,
			prior = 5, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend12",
			idle = 0,
			prior = 20, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			predicate = function(obj_info)
        					return obj_info and obj_info.profile_name == "esc_fanat"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_lager_defend13",
			idle = 0,
			prior = 20, state = {2},
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			predicate = function(obj_info)
        					return obj_info and (obj_info.profile_name == "esc_wolf"
								and not (has_alife_info("agroprom_military_case_have")
								and has_alife_info("esc_fanat_spawn")))
						end
		}
		table.insert(sj, t)
	elseif type == "esc_fabrika_bandit" then	--' Bandits in the factory
		t = { section = "logic@esc_fabrika_bandit_walker1",		-- Happy hour
			idle = 0,
			prior = 2, state = {0},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_fabrika_bandit_walker2",
			idle = 0,
			prior = 2, state = {0},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_fabrika_bandit_walker3",
			idle = 0,
			prior = 2, state = {0},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_fabrika_bandit_walker4",
			idle = 5,
			prior = 10, state = {0,2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor",
				predicate = function(obj_info)
        					return obj_info.name == "esc_factory_prisoner_guard"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_fabrika_bandit_kamp",		-- sitting by the campfire
			idle = 0,
			prior = 1, state = {0},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_fabrika_bandit_kamp",
			idle = 0,
			prior = 1, state = {0},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "camper@esc_fabrika_bandit_walker1",		-- alarm
			idle = 0,
			prior = 5, state = {2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "camper@esc_fabrika_bandit_walker2",
			idle = 0,
			prior = 5, state = {2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "camper@esc_fabrika_bandit_walker3",
			idle = 0,
			prior = 5, state = {2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
--		t = { section = "camper@esc_fabrika_bandit_walker4",
--			idle = 0,
--			prior = 5, state = {2},
--			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
--		}
--		table.insert(sj, t)
		t = { section = "camper@esc_fabrika_bandit_walker5",
			idle = 0,
			prior = 2, state = {2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "camper@esc_fabrika_bandit_walker6",
			idle = 0,
			prior = 2, state = {2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "camper@esc_fabrika_bandit_walker7",
			idle = 0,
			prior = 5, state = {0,2},
			in_rest = "esc_prison_zone", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
	elseif type == "esc_bridge" then	--' Soldiers on the bridge
		-- Happy hour
		t = { section = "logic@esc_bridge_post1",
			idle = 0,
			prior = 7, state = {0},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_post2",
			idle = 0,
			prior = 15, state = {0,1},
			in_rest = "", out_rest = "escape_bridge_zone",
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_soldier_commander"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_post3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_post4",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_post5",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_post6",
			idle = 0,
			prior = 8, state = {0,1},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_kamp1",
			idle = 0,
			prior = 2, state = {1},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_kamp3",
			idle = 0,
			prior = 2, state = {1},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_kamp4",
			idle = 0,
			prior = 2, state = {1},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_patrol",
			idle = 0,
			prior = 5, state = {1},
			in_rest = "", out_rest = "escape_bridge_zone"
		}
		table.insert(sj, t)
	elseif type == "esc_killers" then							--' Mercenaries attacking newcomers.
		t = { section = "logic@esc_killer_leader_raid",
			idle = 0,
			prior = 10, state = {4},
			in_rest = "", out_rest = "",
			online = true,
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_killer_master"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer1_raid",
			idle = 0,
			prior = 8, state = {4},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer2_raid",
			idle = 0,
			prior = 8, state = {4},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer1_follower",
			idle = 0,
			prior = 7, state = {4},
			online = true,
			in_rest = "", out_rest = "",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer1_follower",
			idle = 0,
			prior = 7, state = {4},
			online = true,
			in_rest = "", out_rest = "",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer2_follower",
			idle = 0,
			prior = 7, state = {4},
			online = true,
			in_rest = "", out_rest = "",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer2_follower",
			idle = 0,
			prior = 7, state = {4},
			online = true,
			in_rest = "", out_rest = "",
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 15, state = {1},
			online = true,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone",
			position_threshold = 400,
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_killer_master"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_fight",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = "esc_lager_guard_kill_zone"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 15, state = {2},
			in_rest = "", out_rest = "",
			position_threshold = 400,
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_killer_master"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_wait",
			idle = 0,
			prior = 5, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_wait",
			idle = 0,
			prior = 5, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_wait",
			idle = 0,
			prior = 5, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_wait",
			idle = 0,
			prior = 15, state = {3},
			in_rest = "", out_rest = "",
			online = true,
			position_threshold = 400,
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_killer_master"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_wait",
			idle = 0,
			prior = 5, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_guard1",
			idle = 0,
			prior = 8, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_guard2",
			idle = 0,
			prior = 8, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_guard3",
			idle = 0,
			prior = 8, state = {3},
			online = true,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_killer_kamp_offline",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 400,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_dogs_to_fox" then
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox_home",
			idle = 0,
			prior = 5, state = {2},
			position_threshold = 100,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox",
			idle = 0,
			prior = 5, state = {1},
			position_threshold = 100,
			in_rest = "", out_rest = "esc_dogs_fox_attack"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox",
			idle = 0,
			prior = 5, state = {1},
			position_threshold = 100,
			in_rest = "", out_rest = "esc_dogs_fox_attack"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox",
			idle = 0,
			prior = 5, state = {1},
			position_threshold = 100,
			in_rest = "", out_rest = "esc_dogs_fox_attack"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox",
			idle = 0,
			prior = 5, state = {1},
			position_threshold = 100,
			in_rest = "", out_rest = "esc_dogs_fox_attack"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_to_fox",
			idle = 0,
			prior = 5, state = {1},
			position_threshold = 100,
			in_rest = "", out_rest = "esc_dogs_fox_attack"
		}
		table.insert(sj, t)
	elseif type == "esc_dogs_swarm" then
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm1",
			idle = 0,
			prior = 5, state = {0},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm3",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_dogs_swarm2",
			idle = 0,
			prior = 5, state = {2},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_boars_dogs" then
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs_old",
			idle = 0,
			prior = 5, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_boars_dogs",
			idle = 0,
			prior = 5, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_ambush" then
		t = { section = "logic@esc_ambush1",
			idle = 0,
			prior = 8, state = {0},
			in_rest = "", out_rest = "esc_ambush_out_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_ambush2",
			idle = 0,
			prior = 8, state = {0},
			in_rest = "", out_rest = "esc_ambush_out_restrictor"
		}
		table.insert(sj, t)
	elseif type == "esc_corps" then
		t = { section = "logic@esc_corps_wounded",
			idle = 4,
			prior = 10, state = {0},
			online = false,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_vagon_wounded"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_corps_wounded",
			idle = 0,
			prior = 10, state = {1},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_vagon_wounded"
						end
		}
		table.insert(sj, t)
	elseif type == "esc_assault" then
		t = { section = "logic@esc_assault1",
			idle = 0,
			prior = 8, state = {1},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault2",
			idle = 0,
			prior = 9, state = {1},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker2"
						end			
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault3",
			idle = 0,
			prior = 10, state = {1},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker1"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault1",
			idle = 0,
			prior = 8, state = {0},
			online = false,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault2",
			idle = 0,
			prior = 9, state = {0},
			online = false,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker2"
						end			
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault3",
			idle = 0,
			prior = 10, state = {0},
			online = false,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker1"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_fight1",
			idle = 0,
			prior = 8, state = {2},
			online = true,
			position_threshold = 100,
			in_rest = "", out_rest = "esc_fabrika_bandit_space_restrictor"
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_fight2",
			idle = 0,
			prior = 9, state = {2},
			online = true,
			position_threshold = 100,
			in_rest = "", out_rest = "esc_fabrika_bandit_space_restrictor",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker2"
						end			
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_fight3",
			idle = 0,
			prior = 10, state = {2},
			online = true,
			position_threshold = 100,
			in_rest = "", out_rest = "esc_fabrika_bandit_space_restrictor",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker1"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_home1",
			idle = 0,
			prior = 8, state = {3},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_home2",
			idle = 0,
			prior = 9, state = {3},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker2"
						end			
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_home_leader",
			idle = 0,
			prior = 10, state = {3},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker1"
						end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_kamp",
			idle = 0,
			prior = 8, state = {4},
			online = true,
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_kamp",
			idle = 0,
			prior = 9, state = {4},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker2"
						end			
		}
		table.insert(sj, t)
		t = { section = "logic@esc_assault_kamp",
			idle = 0,
			prior = 10, state = {4},
			online = true,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
        					return obj_info and obj_info.name == "esc_novice_attacker1"
						end
		}
		table.insert(sj, t)
	elseif type == "esc_zombie_1" then
		t = { section = "logic@esc_zombie_1_fd",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_fd",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_3_fd",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_4_fd",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_5_fd",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_6_fd",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_zombie_2" then
		t = { section = "logic@esc_zombie_2_home",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_zombie_2_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_flesh_1" then
		t = { section = "logic@esc_flesh_1_camp",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_flesh_1_camp",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_flesh_1_camp",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_flesh_2" then
		t = { section = "logic@esc_flesh_2_camp",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_flesh_2_camp",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_flesh_2_camp",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_bridge_boar" then
		t = { section = "logic@esc_bridge_boar",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_boar",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_boar",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_boar",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_bridge_boar",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_small_home1" then
		t = { section = "logic@esc_small_home1",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home1",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_small_home2" then
		t = { section = "logic@esc_small_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home2",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_small_home3" then
		t = { section = "logic@esc_small_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home3",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_small_home4" then
		t = { section = "logic@esc_small_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home4",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_small_home5" then
		t = { section = "logic@esc_small_home5",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home5",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_small_home6" then
		t = { section = "logic@esc_small_home6",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
		t = { section = "logic@esc_small_home6",
			idle = 0,
			prior = 5, state = {0},
			in_rest = "", out_rest = ""
		}
		table.insert(sj, t)
	elseif type == "esc_stalker_camp" then
		t = { section = "logic@esc_stalker_camp_provodnik",
			idle = 0,
			prior = 10, state = {0},
			online = false,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_provodnik"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_stalker_fox",
			idle = 0,
			prior = 10, state = {0},
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_fox"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_stalker_camp_provodnik",
			idle = 0,
			prior = 10, state = {1},
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_provodnik"
			            end
		}
		table.insert(sj, t)
		t = { section = "logic@esc_stalker_camp1",
			idle = 0,
			prior = 8, state = {1},
			online = false,
			in_rest = "", out_rest = "",
			predicate = function(obj_info)
			            	return obj_info and obj_info.profile_name == "esc_fox"
			            end
		}
		table.insert(sj, t)
	else
		--TB3D_Services.packet_alert("gulag escape: load job for type["..utils.to_str(type).."] not found")
	end
end

function load_states(gname, type)
	if type == "aver_hunter" then
        return function(gulag) return 0 end
	elseif type == "warlab_svobodovzu" then
        return function(gulag) return 0 end
	elseif type == "atp_brigada" then				--- Kalinin ---
        return function(gulag) return 0 end
	elseif type == "aver_otshelnik" then			--- Hermit ---
        return function(gulag) return 0 end
	elseif type == "esc_new_lager" then				--- new camp kostya ---
        return function(gulag) return 0 end
	elseif type == "svalka_lager" then				--- svalka camp kostya---
        return function(gulag) return 0 end
	elseif type == "bar_lager" then					--- bar camp kostya---
        return function(gulag) return 0 end
	elseif type == "as_lager" then					--- as camp kostya---
        return function(gulag) return 0 end
	elseif type == "pripyat_lager" then				--- pripyat camp kostya---
        return function(gulag) return 0 end
	elseif type == "labirint_monolit" then
        return function(gulag) return 0 end
	elseif type == "land_arhara_sniper" then
        return function(gulag) return 0 end
	elseif type == "aver_arhara_sniper_mikrogulag1" then
        return function(gulag) return 0 end
	elseif type == "aver_arhara_sniper_makrogulag2" then
        return function(gulag) return 0 end
	elseif type == "atp_fabrika_bandit" then
        return function(gulag) return 0 end
	elseif type == "village_gulag_big" then
        return function(gulag) return 0 end
	elseif type == "village_gulag_small" then
        return function(gulag) return 0 end
	elseif type == "lost_village_bandit" then
        return function(gulag) return 0 end
	elseif type == "generators_orly" then
        return function(gulag) return 0 end
	elseif type == "black_generators" then
        return function(gulag) return 0 end
	elseif type == "generators_svoboda" then
        return function(gulag) return 0 end
	elseif type == "hospital_black" then
        return function(gulag) return 0 end
	elseif type == "rost_naem_koster" then
        return function(gulag) return 0 end
	elseif type == "esc_podmoga_bandit" then
        return function(gulag) return 0 end
	elseif type == "dead_city_stalkers" then
        return function(gulag) return 0 end
	elseif type == "dead_city_banda" then
        return function(gulag) return 0 end
	elseif type == "dead_city_naymitu" then
        return function(gulag) return 0 end
	elseif type == "esc_blokpost" then
		return function (gulag)
			--if not (db.actor) and (gulag) then return gulag.state end
			if (gulag) then
				if gulag.alarm_start == nil or game.get_game_time():diffSec(gulag.alarm_start) > 300 then
					for k,v in pairs(gulag.Object) do
						if v ~= true and v:best_enemy() ~= nil and v:see(v:best_enemy()) then
							gulag.alarm_start = game.get_game_time()
							TB3D_Services.give_info("esc_blockpost_alarm")
							return 2 -- anxiety
						end
					end
					TB3D_Services.give_info("esc_blockpost_normal")
					if TB3D_Services.is_night(false) == true then return 1 else return 0 end
				else return gulag.state end
			end
			TB3D_Services.give_info("esc_blockpost_normal")
			if TB3D_Services.is_night(false) == true then return 1 else return 0 end
		end
	elseif type == "esc_lager" then
		return function(gulag)
			--if not (db.actor) and (gulag) then return gulag.state end
			if has_alife_info("escape_lager_help") and not has_alife_info("escape_lager_killers_die") then
				return 2 -- defend camp
			elseif TB3D_Services.is_night(false) == true then return 1 else return 0 end
		end
	elseif type == "esc_bridge" then
		return function(gulag)
			--if not (db.actor) and (gulag) then return gulag.state end
			if TB3D_Services.is_night(false) == true then return 1 else return 0 end
		end
	elseif type == "esc_fabrika_bandit" then
		return function(gulag)
			if gulag then
				for k,v in pairs(gulag.Object) do
					if v ~= true and v:best_enemy() ~= nil then
   						gulag.alarm_start = game.get_game_time()
   						return 2 -- alarmed
					end
				end
				if gulag.alarm_start == nil or
					game.get_game_time():diffSec(gulag.alarm_start) > 300 then
					--return 0  -- guarding
				else
					return 2
				end
			end
			if TB3D_Services.is_night(false) == true then return 1 else return 0 end
			--return 0
		end
	elseif type == "esc_dogs_to_fox" then
		return function(gulag)
			if not has_alife_info("escape_stalker_dog_spawn") then
				return 0 -- offline
			elseif (has_alife_info("escape_stalker_dog_spawn") and not has_alife_info("escape_stalker_done")) or has_alife_info("esc_dogs_return") then 
				return 2 -- online
			else
				return 1 -- attack
			end
			return 0 -- offline
		end
	elseif type == "esc_specnaz" then
		return function(gulag)
			if has_alife_info("esc_raid1_start") then
				return 1
			end
			return 0
		end
	elseif type == "esc_boars_dogs" then
	    return function(gulag)
			if has_alife_info("tutorial_wounded_give_info") then
				return 1
			else
				return 0
			end
		end
	elseif type == "esc_killers" then
		return function(gulag)
			--if not (db.actor) and (gulag) then return gulag.state end
			if not has_alife_info("escape_lager_spawn_killers") then
				return 0 -- offline
			elseif has_alife_info("escape_lager_spawn_killers")
			  and not has_alife_info("esc_killers_raid") then
				return 3 -- wait
			elseif has_alife_info("esc_killers_raid")
			  and not has_alife_info("esc_open_killer_fire") then
				return 4 -- raid
			elseif has_alife_info("esc_open_killer_fire")
			  and xr_gulag.getGulagPopulationComed("esc_lager") > 0 then
				return 1 -- fight
			elseif has_alife_info("esc_open_killer_fire")
			  and xr_gulag.getGulagPopulationComed("esc_lager") <= 0 then
				return 2 -- camp
			end
			--if gulag then return gulag.state else return 0 end
			return 0
		end
	elseif type == "esc_dogs_swarm" then
		return function(gulag)
			--if not (db.actor) and (gulag) then return gulag.state end
			if gulag then
				if game.get_game_time():diffSec(gulag.stateBegin) > 900 then
					if gulag.state == 0 then
						return 1
					elseif gulag.state == 1 then
						return 2
					elseif gulag.state == 2 then
						return 0
					end
				else
					return gulag.state
				end
			end
			return 0
		end
	elseif type == "esc_ambush" then
		return function(gulag) return 0 end
	elseif type == "esc_corps" then
		return function(gulag)
			--if not (db.actor) and (gulag) then return gulag.state end
			if has_alife_info("tutorial_wounded_start") then
				return 1
			else
				return 0
			end
		end
	elseif type == "esc_zombie_1" then
        return function(gulag) return 0 end
	elseif type == "esc_zombie_2" then
        return function(gulag) return 0 end
	elseif type == "esc_flesh_1" then
        return function(gulag) return 0 end
	elseif type == "esc_flesh_2" then
        return function(gulag) return 0 end
	elseif type == "esc_bridge_boar" then
        return function(gulag) return 0 end
	elseif type == "esc_small_home1" then
        return function(gulag) return 0 end
	elseif type == "esc_small_home2" then
        return function(gulag) return 0 end
	elseif type == "esc_small_home3" then
        return function(gulag) return 0 end
	elseif type == "esc_small_home4" then
        return function(gulag) return 0 end
	elseif type == "esc_small_home5" then
        return function(gulag) return 0 end
	elseif type == "esc_small_home6" then
        return function(gulag) return 0 end
    elseif type == "generators_flesh1" then        
        return function(gulag) return 0 end
    elseif type == "generators_gigant" then        
        return function(gulag) return 0 end
    elseif type == "generators_chimera" then        
        return function(gulag) return 0 end
    elseif type == "generators_tushkano" then        
        return function(gulag) return 0 end
    elseif type == "generators_kaban" then       
        return function(gulag) return 0 end
    elseif type == "gener_kaban_two" then        
        return function(gulag) return 0 end
    elseif type == "aver_kaban_gulag" then        
        return function(gulag) return 0 end
    elseif type == "generators_snork" then        
        return function(gulag) return 0 end
	elseif type == "esc_stalker_camp" then
		return function(gulag)
			if has_alife_info("yan_provodnik_spawn") then
				return 1
			else
				return 0
			end
		end
	elseif type == "esc_assault" then
		return function(gulag)
			if has_alife_info("esc_kill_bandits_quest_have")
			  and not has_alife_info("esc_kill_bandits_quest_done")
			  and not has_alife_info("esc_assault_start") then
				return 1 -- sit by the campfire
			elseif has_alife_info("esc_assault_start")
			  and not has_alife_info("esc_kill_bandits_quest_kill") then
				return 2 -- attack the factory
			elseif has_alife_info("esc_kill_bandits_quest_kill")
			  and (not has_alife_info("esc_kill_bandits_quest_done")
			  or not has_alife_info("esc_petruha_great")) then
				return 3 -- go home	
			elseif has_alife_info("esc_kill_bandits_quest_done")
			  or has_alife_info("esc_petruha_great") then
				return 4 -- go home
			else
				return 0 -- sit Offline
			end
		end
	end
	return nil
end

--------------------------------------------------------------------------
-- Dynamic ltx
--------------------------------------------------------------------------
function load_ltx(gname, type)
	return nil
end

function checkStalker(npc_community, gulag_type, npc_rank, se_obj)

if gulag_type == "warlab_svobodovzu" then
        return npc_community == "freedom"
    end

if gulag_type == "aver_hunter" then
        return npc_community == "green"
    end

--- Kalinin ---
	if gulag_type == "atp_brigada" then
		return npc_community == "stalker"
	end

--- Hermit ---
	if gulag_type == "aver_otshelnik" then
		return npc_community == "stalker"
	end

	--- new camp ---
	if gulag_type == "esc_new_lager" then
		return se_obj:profile_name() == "esc_kostya"
	end 
	
	--- svalka camp ---
	if gulag_type == "svalka_lager" then
		return se_obj:profile_name() == "esc_kostya"
	end 
	
	--- bar camp ---
	if gulag_type == "bar_lager" then
		return se_obj:profile_name() == "esc_kostya"
	end 
	
	--- as camp ---
	if gulag_type == "as_lager" then
		return se_obj:profile_name() == "esc_kostya"
	end 
	
	--- pripyat camp ---
	if gulag_type == "pripyat_lager" then
		return se_obj:profile_name() == "esc_kostya"
	end

    if gulag_type == "labirint_monolit" then
		return npc_community == "monolith"
	end

    if gulag_type == "land_arhara_sniper" then
		return npc_community == "sniper"
	end

    if gulag_type == "aver_arhara_sniper_mikrogulag1" then
		return npc_community == "sniper"
	end

    if gulag_type == "aver_arhara_sniper_makrogulag2" then
		return npc_community == "sniper"
	end

    if gulag_type == "atp_fabrika_bandit" then
		return npc_community == "bandit"
	end

    if gulag_type == "village_gulag_big" then
		return npc_community == "stalker"
	end

    if gulag_type == "village_gulag_small" then
		return npc_community == "stalker"
	end

    if gulag_type == "lost_village_bandit" then
		return npc_community == "bandit"
	end

    if gulag_type == "generators_orly" then
		return npc_community == "stalker"
	end

    if gulag_type == "black_generators" then
		return npc_community == "stalker"
	end

    if gulag_type == "generators_svoboda" then
		return npc_community == "freedom"
	end

    if gulag_type == "hospital_black" then
		return npc_community == "stalker"
	end

    if gulag_type == "rost_naem_koster" then
		return npc_community == "killer"
	end

    if gulag_type == "esc_podmoga_bandit" then
		return npc_community == "bandit"
	end

    if gulag_type == "dead_city_stalkers" then
		return npc_community == "stalker"
	end

    if gulag_type == "dead_city_banda" then
		return npc_community == "bandit"
	end

     if gulag_type == "dead_city_naymitu" then
		return npc_community == "killer"
	end
	
	if gulag_type == "esc_bridge" then
		return npc_community == "military"
	end

	if gulag_type == "esc_specnaz" then
		return se_obj:profile_name() == "esc_soldier_specnaz"
	end

	if gulag_type == "esc_blokpost" then
		return npc_community == "military"
	end

	if gulag_type == "esc_killers" then
		return npc_community == "killer"
	end

	if gulag_type == "esc_lager" then
		return npc_community == "stalker"
	end

	if gulag_type == "esc_fabrika_bandit" then
		return npc_community == "bandit"
	end

	if gulag_type == "esc_ambush" then
		return npc_community == "bandit"
	end

	if gulag_type == "esc_corps" then
		return npc_community == "stalker"
	end

	if gulag_type == "esc_assault" then
		return npc_community == "stalker"
	end

	if gulag_type == "esc_stalker_camp" then
		return npc_community == "stalker"
	end
	
	return false
end

function checkMonster(npc_community, gulag_type)

	if gulag_type == "esc_dogs_to_fox" then
		return npc_community == "dog"
	end

	if gulag_type == "esc_dogs_swarm" then
		return npc_community == "dog"
	end

	if gulag_type == "esc_boars_dogs" then
		return npc_community == "dog" or
			npc_community == "boar"
	end

	if gulag_type == "esc_zombie_1" then
		return npc_community == "zombie"
	end

	if gulag_type == "esc_zombie_2" then
		return npc_community == "zombie"
	end

	if gulag_type == "esc_flesh_1" then
		return npc_community == "flesh"
	end

	if gulag_type == "esc_flesh_2" then
		return npc_community == "flesh"
	end
	
	if gulag_type == "esc_bridge_boar" then
		return npc_community == "boar"
	end
	
	if gulag_type == "esc_small_home1" then
		return npc_community == "boar"
	end
	
	if gulag_type == "esc_small_home2" then
		return npc_community == "boar"
	end
	
	if gulag_type == "esc_small_home3" then
		return npc_community == "dog"
	end
	
	if gulag_type == "esc_small_home4" then
		return npc_community == "dog"
	end
	
	if gulag_type == "esc_small_home5" then
		return npc_community == "dog"
	end

     if gulag_type == "generators_flesh1" then
          return npc_community == "flesh"
     end

     if gulag_type == "generators_gigant" then
          return npc_community == "pseudo_gigant"
     end

     if gulag_type == "generators_chimera" then
          return npc_community == "chimera"
     end

     if gulag_type == "generators_tushkano" then
          return npc_community == "tushkano"
     end

     if gulag_type == "generators_kaban" then
          return npc_community == "boar"
     end

     if gulag_type == "gener_kaban_two" then
          return npc_community == "boar"
     end

     if gulag_type == "aver_kaban_gulag" then
          return npc_community == "boar"
     end

     if gulag_type == "generators_snork" then
          return npc_community == "snork"
     end
	
	if gulag_type == "esc_small_home6" then
		return npc_community == "flesh"
	end
	
	return false
end