//TB3D 109993 Adapted from Meltac 2.0 DX11 shaders
#include"refraction.h"
#ifdef WET_REFBLUR
#include"blur.h"
#endif
float4 decolor(float4 f):COLOR{f.x*=5;float i=.7,w=.6,z=dot(f.xyz,float3(.3,.59,.11));f.xyz=lerp(float3(z,z,z),f.xyz,i+dot(Ldynamic_color.xyz,float3(1,1,1))/3*w);return f;}float4 checkwet(float2 f,bool s):COLOR{float4 i;i=tex2Dlod(s_image,float4(f.xy,0,0));float3 w=tex2Dlod(s_position,float4(f,0,0)).xyz;float4 W=tex2Dlod(s_bloom,float4(f,0,0));float z=(i.x+i.y+i.z)/3;if(s)W/=L_hemi_color;else W=W/L_hemi_color/Ldynamic_color/float4(L_sun_color,1)/3;float x=.08,b=.3,y=.86,L=W.z/((W.x+W.y+W.z)/3);if(W.z>x&&W.x<b&&W.y<b&&L>y&&z>WET_MINLUM&&w.z<WET_MAXDIST){float d=saturate((W.z-x+.01)*(b-W.x+.01)*(b-W.y+.01)*(L-y+.01)*.1*100000);i.w=.1;}else i.w=1.;return i;}float4 decolorize(float2 f,bool i):COLOR{float4 W=checkwet(f,i);if(W.w==.1)W=decolor(W);return W;}float4 normalize_blue(float4 f):COLOR{return float4(f.x/f.z,f.y/f.z,1,f.w);}
#ifdef WET_OBJREFLECT
float4 objreflect(float4 i,float4 f,int W,bool z,bool x,float2 s:TEXCOORD,float n,float e,float t,float w,float d):COLOR{float y=.5;bool b=false;float L=f.z,r=0,p=0,m=0;float4 o=0;int l=W,P=0;if((W==2||W==1&&(z||x))&&f.z<WET_OBJMAXDISTCOL){float c=1.f/768.f,M=WET_OBJSTEP/768.f;for(int R=1;R<=WET_OBJSAMPLES;R++){if(!b){float a=s.y-M*R;float4 E=tex2Dlod(s_position,float4(s.x,a,0,0));l=mcls(E.w);if(E.z<WET_OBJMAXDISTREF){r=L+WET_OBJDEPTH;p=f.z;L=E.z;if(l!=W)y=a,b=true,m=E.z,o=E,P=R;}}}int a=l;if(b){for(int E=0;E<=WET_OBJSTEP+5;E++){if(b){float D=y+c*E;float4 S=tex2Dlod(s_position,float4(s.x,D,0,0));a=mcls(S.w);r=(L-WET_OBJDEPTH/WET_OBJSTEP)*1;L=S.z;if(l!=W&&a==W)y=D,m=S.z,o=S;else b=false;}}b=true;}float E=y;if(m>0){o.xyz=mul(o.xyz,(float3x3)m_WV).xyz;float D=distance(float2(0,0),o.xz),S=mul(f,(float3x3)m_WV).y,F=.8,H=4.f,T=-.00995*100+-.0075*100*S;y=T/m+.5f+.5f*saturate(.5f/pow(m,1))*H;float V=normalize(eye_direction).y;if(V<=-.6)F=.88;else if(V>-.6&&V<=-.55)F=.85;else if(V>-.55&&V<=-.5)F=.83;else if(V>-.5&&V<=-.4)F=.8;else if(V>-.4&&V<=-.2)F=.79;else F=.78;y=y+V*F;if(V<0){float A=abs(V)*1.5;y=lerp(y,E,A);}}float F=WET_OBJWAVE,V=-(s.y-y)+y+sin(f.y*100*e*F/pow(n,2))*.03;if(V>y||V<0)b=false;if(b){float4 S=0;float D=d*WET_DISAMP,T=d*WET_DISFRQ,A=d*WET_DISPER;float2 H=xrefract(float2(s.x,V),D,T,A,pow(n,.5),0);H=xrefract(H,D,T,A,pow(n,.5),timers.x);s.x=H.x;V=H.y;float4 Q=tex2Dlod(s_bloom,float4(s.x,V,0,0));if(W!=1||z)S=tex2Dlod(s_image,float4(s.x,V,0,0)),S=lerp(Q,S,saturate((1-WET_BLOOM)*w-WET_RAINBLOOM*d));else S=Q;float4 O=tex2Dlod(s_position,float4(s.x,V,0,0));int u=mcls(O.w);r=L+WET_OBJDSTCORR;if(O.z>r)b=false;if(b&&u!=3&&u!=4&&S.w<WET_MAXALPHA){float B=pow(saturate(1-(float)P/(float)WET_OBJSAMPLES),WET_OBJFADE)*10;w=saturate(10*w*n*B);if(w>WET_OBJMAXREF)w=WET_OBJMAXREF;t*=saturate(1-w)*1.8;i=t*i+w*S;}}}return i;}
#endif
