--TB3D 1.0.9.9.7.5
--optional file presently used for testing

function init()			--called  from bind_stalker.net_spawn()
	-------------------------------------test setcion-------------------------------------------
	--TB3D_Services.move_actor(-40.398349761963,-21.837560653687,56.543983459473)
	--tb3d_net_manager.network_send("test")
	--------------------------------------------------------------------------------------------
end