--TB3D 1.0.9.9.7.5
--optional file presently used for testing

function init()			--called  from bind_stalker.net_spawn()
	-------------------------------------test setcion-------------------------------------------
	--TB3D_Services.move_actor(-19.5539226531982,-4.34696102142334,329.650390625)
	--tb3d_net_manager.network_send("test")
	--------------------------------------------------------------------------------------------
end